TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# abuse .db rules to install screens

INSTALL_DB = $(INSTALL_LOCATION)/opi

DB += feed_base.bob

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
