TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB += feed_logic_array_mask.template
DB += feed_logic_decim.template
DB += feed_logic_fanout.template
DB += feed_logic_pair_power.template
DB += feed_logic_pair.template
DB += feed_logic_read.template
DB += feed_logic_signal.template
DB += feed_logic_stats.template
DB += feed_logic_trigger.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
