TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

LIBRARY += feedcom

feedcom_LIBS += Com
feedcom_SYS_LIBS += z

feedcom_SRCS += jblob.cpp
feedcom_SRCS += zpp.cpp

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

