
name: pytest

on: [push, pull_request, workflow_dispatch]

jobs:
    pytest:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ['3.10', '3.11', '3.12', '3.x']

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Deps
          run: pip install pytest pytest-cov numpy
        - name: Test
          run: cd src/python && python -m pytest -v --log-level=DEBUG
